version: "3.9"

services:
  tbh:
    image: postgres:15.3
    ports:
      - "5433:5432"
    volumes:
      - db_data_pg:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tbhong

volumes:
  db_data_pg:
